auth:
  username: the-user
  password: the-password
  securePassword: false
  tls:
    enabled: false
clustering:
  enabled: false

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "1000m"
